name: Deploy CheckRegistry

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "contract/check-registry-chain/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: contract/check-registry-chain

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Create .env.production
        run: |
          cat <<EOF > .env.production
          ACTION=deploy
          POLYGON_AMOY_RPC=${{ secrets.POLYGON_AMOY_RPC }}
          PRIVATE_KEY=${{ secrets.DEPLOYER_PRIVATE_KEY }}
          CONTRACT_ADDRESS=
          REGISTER_ADMIN=${{ secrets.REGISTER_ADMIN }}
          VOID_ADMIN=${{ secrets.VOID_ADMIN }}
          EOF

      - name: Deploy + verify
        run: npx hardhat run scripts/check-registry.js --network polygon_amoy
        env:
          NODE_ENV: production
